services:
  - type: web
    name: flight-backend
    env: python
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT backend.app:app --access-logfile - --error-logfile - --timeout 120
    plan: free
